Resources:
    NATGateway:
        Type: AWS::EC2::NatGateway
        Properties:
            AllocationId: !GetAtt NATGatewayEIP.AllocationId
            SubnetId: !ImportValue SubnetPublic1A
            Tags:
                - Key: Name
                  Value: !Ref AWS::StackName           
                - Key: networking
                  Value: nat-gateway           
    NATGatewayEIP:
        Type: AWS::EC2::EIP
        Properties:
            Domain: vpc
        
    RouteNATGateway:
        DependsOn: NATGateway
        Type: AWS::EC2::Route
        Properties:
            RouteTableId: !ImportValue RouteTablePrivateId
            DestinationCidrBlock: '0.0.0.0/0'
            NatGatewayId: !Ref NATGateway